# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_auto_20160524_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.ImageFolder'),
        ),
    ]
